name: Android CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: |
        chmod +x gradlew
        # yes | sdkmanager "platforms;android-28"
        # yes | sdkmanager "build-tools;28.0.3"
    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace -w
